MODEL:
    NAME: 'resnetv2_152x2_bitm'
    DIR: 'results/resnetv2_152x2_bitm'
    INPUT_SIZE: 448
    MEAN: [ 0.485, 0.456, 0.406 ]
    STD: [ 0.229, 0.224, 0.225 ]
DATASET:
    NAME: 'MURA'
TRAIN:
    BATCH_SIZE: 8
    LEARNING_RATE: 5e-4