MODEL:
    NAME: 'vit_large_patch16_384'
    DIR: 'results/vit_large_patch16_384'
    INPUT_SIZE: 384
    MEAN: [0.5, 0.5, 0.5]
    STD: [0.5, 0.5, 0.5]
DATASET:
    NAME: 'MURA'
TRAIN:
    BATCH_SIZE: 8